server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: # EXTERNAL
    username: # EXTERNAL
    password: # EXTERNAL
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
jwt:
  secret: # EXTERNAL
  expirationInMs: # EXTERNAL