server:
  port: 8080

spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: # EXTERNAL
    username: # EXTERNAL
    password: # EXTERNAL
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
liquibase:
  manual: true
jwt:
  secret: # EXTERNAL
  expirationInMs: # EXTERNAL